export const AUTOCOMPLETE_SEARCH_LIST_SUCCESS =
	"AUTOCOMPLETE_SEARCH_LIST_SUCCESS";
export const AUTOCOMPLETE_SEARCH_LIST_FAIL = "AUTOCOMPLETE_SEARCH_LIST_FAIL";

export const AUTOCOMPLETE_SEARCH_LOCATION_SUCCESS =
	"AUTOCOMPLETE_SEARCH_LOCATION_SUCCESS";
export const AUTOCOMPLETE_SEARCH_LOCATION_FAIL =
	"AUTOCOMPLETE_SEARCH_LOCATION_FAIL";

export const CURRENT_CONDITION_SUCCESS = "CURRENT_CONDITION_SUCCESS";
export const CURRENT_CONDITION_FAIL = "CURRENT_CONDITION_FAIL";

export const FIVE_DAYS_CONDITION_SUCCESS = "FIVE_DAYS_CONDITION_SUCCESS";
export const FIVE_DAYS_CONDITION_FAIL = "FIVE_DAYS_CONDITION_FAIL";
